from filtro_temporada import filtro_temporada
from frequencia_minima import frequencia_minima
from temporada_gols import temporada_gols
from temporada_media_gols import temporada_media_gols
from temporada_partidas_jogadas import temporada_partidas_jogadas
